### ISSUE TITLE
Does not work with tagged restas

### ISSUE THREAD

**Issue by quicklisp** [archimag/restas-directory-publisher#1]
I'm using the latest tag of restas, and restas-directory-publisher HEAD does not work with it due to an unexported symbol `initialize-module-instance`. What version of restas-directory-publisher should I use? Or should I update restas somehow? I haven't used restas HEAD because it is incompatible with the released version of hunchentoot. Any guidance would be appreciated.

**Comment by archimag** [comment]
Yeah, I forgot about it. I made a "version-0.1" tag for restas-directory-publisher - it must be compatible with restas-0.1.3

**Comment by quicklisp** [comment]
Thanks, pulling version-0.1 works fine.
